// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJiHlVH-uuQ7FAibwD61yxwnwi0EYdrTY',
    appId: '1:954821898568:web:129402ccb8ac79628dc37d',
    messagingSenderId: '954821898568',
    projectId: 'ahrumiki',
    authDomain: 'ahrumiki.firebaseapp.com',
    databaseURL: 'https://ahrumiki-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ahrumiki.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1bcfvrcx4THPX1_b1Lu4HIe7R2nsp-0Q',
    appId: '1:954821898568:android:d34adb6ef976a6728dc37d',
    messagingSenderId: '954821898568',
    projectId: 'ahrumiki',
    databaseURL: 'https://ahrumiki-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ahrumiki.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX45W5_rTfk7FsBDjJWyTmDhm2_T9pYpI',
    appId: '1:954821898568:ios:88c4b17d521a80a48dc37d',
    messagingSenderId: '954821898568',
    projectId: 'ahrumiki',
    databaseURL: 'https://ahrumiki-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ahrumiki.appspot.com',
    iosBundleId: 'com.example.pbl4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX45W5_rTfk7FsBDjJWyTmDhm2_T9pYpI',
    appId: '1:954821898568:ios:88c4b17d521a80a48dc37d',
    messagingSenderId: '954821898568',
    projectId: 'ahrumiki',
    databaseURL: 'https://ahrumiki-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ahrumiki.appspot.com',
    iosBundleId: 'com.example.pbl4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJiHlVH-uuQ7FAibwD61yxwnwi0EYdrTY',
    appId: '1:954821898568:web:8958e9f73bbd85c58dc37d',
    messagingSenderId: '954821898568',
    projectId: 'ahrumiki',
    authDomain: 'ahrumiki.firebaseapp.com',
    databaseURL: 'https://ahrumiki-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ahrumiki.appspot.com',
  );
}
